name: Flutter CI/CD

on:
  push:
    branches:
      - main  # S'exécute sur chaque push vers la branche "main"
  pull_request:
    branches:
      - main  # S'exécute sur chaque pull request vers la branche "main"

jobs:
  build:
    runs-on: ubuntu-latest  # Exécute la pipeline sur un runner Ubuntu

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Flutter (dernière version stable)
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Utilise la dernière version stable de Flutter

    # Étape 3 : Vérifier l'environnement Flutter
    - name: Run Flutter Doctor
      run: flutter doctor

    # Étape 4 : Installer les dépendances du projet
    - name: Install dependencies
      run: flutter pub get

    # Étape 5 : Lancer les tests unitaires
    - name: Run tests
      run: flutter test

    # Étape 6 : Lancer l'analyse statique (Dart Analyzer)
    - name: Analyze code
      run: flutter analyze

    # Étape 7 : Construire un APK en mode release (pour Android)
    - name: Build APK
      run: flutter build apk --release

    # Étape 8 (Optionnel) : Construire un IPA en mode release (pour iOS)
    # Cette étape nécessite un runner macOS pour fonctionner
    # - name: Build IPA
    #   runs-on: macos-latest
    #   run: flutter build ios --release
