name: Flutter CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t my-flutter-app:latest .

      # Étape 4 : Exécuter des tests (en utilisant Docker pour standardiser l'environnement)
      - name: Run Flutter Tests
        run: |
          docker run --rm my-flutter-app:latest flutter test

  push-to-registry:
    name: Push Docker Image to Registry
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer l'image Docker locale
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 2 : Pousser l'image Docker dans le registre Docker Hub
      - name: Push Docker Image
        run: |
          docker tag my-flutter-app:latest my-dockerhub-username/my-flutter-app:latest
          docker push my-dockerhub-username/my-flutter-app:latest
